---
name: Lint
on:
  push:
    branches: [main]
  pull_request:
jobs:
  pre-commit:
    uses: darbiadev/.github/.github/workflows/generic-precommit.yaml@142663fca1c211af6a7dccf3a57cac48cfc3c017  # v13.0.5
