---
name: Lint Ansible playbooks
on:
  push:
    branches: [main]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f  # v4.1.3
      - name: Setup Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d  # v5.1.0
        with:
          python-version: 3.x
          allow-prereleases: true
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: Install dependencies
        run: python -m pip install .[ansible,lint_ansible]
      - name: Run ansible lint
        run: |-
          cd ansible
          ansible-lint --offline
