---
name: Lint
on:
  push:
    branches: [main]
  pull_request:
jobs:
  pre-commit:
    uses: darbiadev/.github/.github/workflows/generic-precommit.yaml@91dda16028f109ac78016dd740206fd109740068  # v15.0.0
