---
name: Lint Ansible playbooks
on:
  push:
    branches: [main]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  # v4.2.0
      - name: Setup Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3  # v5.2.0
        with:
          python-version: 3.x
          allow-prereleases: true
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: Install dependencies
        run: python -m pip install .[ansible,lint_ansible]
      - name: Run ansible lint
        run: |-
          cd ansible
          ansible-lint --offline
