---
name: Lint
on:
  push:
    branches: [main]
  pull_request:
jobs:
  pre-commit:
    uses: darbiadev/.github/.github/workflows/generic-precommit.yaml@e3ebedcaeee8d40bdb7ef569dacd74829ab0c368  # v14.0.0
